bind: 0.0.0.0:8080      # address and port to bind on
debug: false
#log-file: log_file_name.log    #optional log file name to log to
allow-transfers: true   # allow log file downloads
follow-names: false     # allow tailing of not-yet-existent files
relative-root: /tailon  # web app root path (default: '')
commands: [tail, grep]  # allowed commands
tail-lines: 10          # number of lines to tail initially
wrap-lines: true        # initial line-wrapping state
extra-files-dir: /etc/tailon/files.d/

files:
  - '/var/log/messages'
  - '/var/log/nginx/*.log'
  - '/var/log/xorg.[0-10].log'
  - '/var/log/nginx/'   # all files in this directory
  - 'cron':             # it's possible to add sub-sections
      - '/var/log/cron*'
  - '192.168.100.113':  #ip address means its on a remote machine, so we need user and password
      user: username
      password: password
      files:            #files or directories on remote machine
      - '/var/log/*.log'
      - '/var/log/nginx/'
